//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pati_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "First name")]
        public string first_name { get; set; }
        [Required]
        [Display(Name = "Surname")]

        public string surname { get; set; }
        public Nullable<int> age { get; set; }
        public string street { get; set; }
        public string house_name_number { get; set; }
        public string region { get; set; }
        public string post_code { get; set; }
        [Required]
        [Display(Name = "Hours per week")]
        public Nullable<double> hours_per_week { get; set; }
    }
}
