//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pati_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class project
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Project name")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Company attached")]
        public Nullable<int> company_id { get; set; }
    
        public virtual company company { get; set; }
    }
}
