//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pati_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class staff_project_allocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff_project_allocation()
        {
            this.staff_time_allocation = new HashSet<staff_time_allocation>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name = "Employee")]
        public Nullable<int> employee_id { get; set; }
        [Required]
        [Display(Name = "Project 1")]
        public Nullable<int> project1_id { get; set; }
        public Nullable<int> project2_id { get; set; }
        [Required]
        [Display(Name = "Project 1 load")]
        public Nullable<int> project1_percentage { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
    
        public virtual staff_project_allocation staff_project_allocation1 { get; set; }
        public virtual staff_project_allocation staff_project_allocation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_time_allocation> staff_time_allocation { get; set; }
    }
}
