//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pati_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class staff_time_allocation
    {
        public int id { get; set; }

        public Nullable<int> allocation_id { get; set; }
        [Required]
        [Display(Name = "Gross salary")]
        public Nullable<decimal> gross_salary { get; set; }
        [Required]
        [Display(Name = "Insurance")]
        public Nullable<decimal> insurance { get; set; }
        [Required]
        [Display(Name = "Pension")]
        public Nullable<decimal> pension { get; set; }
    
        public virtual staff_project_allocation staff_project_allocation { get; set; }
    }
}
